theme: jekyll-theme-cayman
title: "Scaling-up Gene Regulatory Network Simulations"
subtitle: "with an introduction to parallelisation and High Performance Computing"
description: "Scaling-up Gene Regulatory Network Simulations workshop"

markdown: kramdown
kramdown:
  parse_block_html: true
